// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "libs/backend/notification/src/database/prisma/schema.prisma",
  migrations: {
    path: "libs/backend/notification/src/database/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL_NOTIFICATION"],
  },
});
