import * as z from 'zod';
import { roleSchema } from './role.schema';

export const credentialsSchema = z.object({
  id: z.uuid(),
  email: z.email(),
  role: roleSchema,
  passwordHash: z.string().nullable(),
  isVerified: z.boolean(),
  lockedAt: z.date().nullable(),
  lockedUntil: z.date().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

export type Credentials = z.infer<typeof credentialsSchema>;

// Minimal payload passed between services and stored in JWT
export const credentialsPayloadSchema = z.object({
  id: z.uuid(),
  role: roleSchema,
  isVerified: z.boolean(),
});

export type CredentialsPayload = z.infer<typeof credentialsPayloadSchema>;

// Input for creating credentials (id and createdAt are generated by Prisma)
export const createCredentialsSchema = z.object({
  email: z.email(),
  passwordHash: z.string().optional(),
});

export type CreateCredentialsInput = z.infer<typeof createCredentialsSchema>;
