export const API_ROUTES = {
  auth: {
    root: 'auth',
    register: 'auth/register',
    login: 'auth/login',
    logout: 'auth/logout',
    refresh: 'auth/refresh',
    verifyEmail: 'auth/verify-email',
    resendVerification: 'auth/resend-verification',
    forgotPassword: 'auth/forgot-password',
    resetPassword: 'auth/reset-password',
    github: 'auth/github',
    githubCallback: 'auth/github/callback',
    google: 'auth/google',
    googleCallback: 'auth/google/callback',
    sessions: 'auth/sessions',
    sessionById: (sessionId: string) => `auth/sessions/${sessionId}`,
  },
  users: {
    root: 'users',
    me: 'users/me',
    byId: (id: string) => `users/${id}`,
    profile: (id: string) => `users/${id}/profile`,
  },
  chats: {
    root: 'chats',
    direct: 'chats/direct',
    self: 'chats/self',
    byId: (id: string) => `chats/${id}`,
    read: (id: string) => `chats/${id}/read`,
    messages: (id: string) => `chats/${id}/messages`,
    messagesDelta: (id: string) => `chats/${id}/messages/delta`,
    message: (chatId: string, messageId: string) => `chats/${chatId}/messages/${messageId}`,
    forward: (id: string) => `chats/${id}/forward`,
    mediaMessages: (id: string) => `chats/${id}/media/messages`,
    devices: 'chats/devices',
    deviceById: (deviceId: string) => `chats/devices/${deviceId}`,
    prekeys: (deviceId: string) => `chats/devices/${deviceId}/prekeys`,
    senderKeys: (chatId: string) => `chats/${chatId}/sender-keys`,
    chatDevices: (chatId: string) => `chats/${chatId}/devices`,
  },
  search: {
    root: 'search',
    users: 'search/users',
  },
  notifications: {
    root: 'notifications/push',
    pushSubscribe: 'notifications/push/subscribe',
    pushUnsubscribe: 'notifications/push/unsubscribe',
    vapidKey: 'notifications/push/vapid-key',
  },
  media: {
    initUpload: 'media/init-upload',
    confirm: 'media/confirm',
    uploadAvatar: 'media/upload-avatar',
    linkPreview: 'media/link-preview',
    fileUrl: (fileId: string) => `media/files/${fileId}/url`,
    fileContent: (fileId: string) => `media/files/${fileId}/content`,
    delete: (id: string) => `media/${id}`,
    history: 'media/history',
    chatHistory: (chatId: string) => `chats/${chatId}/media/history`,
    userAvatars: (userId: string) => `users/${userId}/avatars`,
    attachmentContent: (chatId: string, messageId: string, attachmentId: string) =>
      `chats/${chatId}/messages/${messageId}/attachments/${attachmentId}/content`,
  },
  admin: {
    users: 'admin/users',
    user: (id: string) => `admin/users/${id}`,
    sessions: (id: string) => `admin/users/${id}/sessions`,
    session: (id: string, sessionId: string) => `admin/users/${id}/sessions/${sessionId}`,
    ban: (id: string) => `admin/users/${id}/ban`,
  },
} as const;

export const CLIENT_ROUTES = {
  root: '/',
  auth: {
    root: '/auth',
    login: '/auth/login',
    register: '/auth/register',
    checkEmail: '/auth/check-email',
    emailVerified: '/auth/email-verified',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  chats: {
    root: '/chats',
    byId: (id: string) => `/chats/${id}`,
  },
  admin: {
    root: '/admin',
    users: '/admin/users',
    user: (id: string) => `/admin/users/${id}`,
    notFound: '/admin/404',
  },
  settings: '/settings',
} as const;
