export const AUTH_PRISMA_REPOSITORY_TOKEN = 'AUTH_PRISMA_REPOSITORY_TOKEN';
export const AUTH_CACHE_REPOSITORY_TOKEN = 'AUTH_CACHE_REPOSITORY_TOKEN';
export const AUTH_SERVICE_TOKEN = 'AUTH_SERVICE_TOKEN';
export const AUTH_CONTROLLER_TOKEN = 'AUTH_CONTROLLER_TOKEN';
export const VERIFICATION_SERVICE_TOKEN = 'VERIFICATION_SERVICE_TOKEN';
