export const CHAT_PRISMA_REPOSITORY_TOKEN = 'CHAT_PRISMA_REPOSITORY_TOKEN';
export const CHAT_SERVICE_TOKEN = 'CHAT_SERVICE_TOKEN';
export const CHAT_CONTROLLER_TOKEN = 'CHAT_CONTROLLER_TOKEN';
export const E2EE_KEY_SERVICE_TOKEN = 'E2EE_KEY_SERVICE_TOKEN';
export const E2EE_KEY_REPOSITORY_TOKEN = 'E2EE_KEY_REPOSITORY_TOKEN';
export const SENDER_KEY_SERVICE_TOKEN = 'SENDER_KEY_SERVICE_TOKEN';
