export const MEDIA_PRISMA_REPOSITORY_TOKEN = 'MEDIA_PRISMA_REPOSITORY_TOKEN';
export const MEDIA_SERVICE_TOKEN = 'MEDIA_SERVICE_TOKEN';
export const MEDIA_CONTROLLER_TOKEN = 'MEDIA_CONTROLLER_TOKEN';
