export const NOTIFICATION_PRISMA_REPOSITORY_TOKEN = 'NOTIFICATION_PRISMA_REPOSITORY_TOKEN';
export const NOTIFICATION_SERVICE_TOKEN = 'NOTIFICATION_SERVICE_TOKEN';
export const NOTIFICATION_CONTROLLER_TOKEN = 'NOTIFICATION_CONTROLLER_TOKEN';
