import type { Params } from 'nestjs-pino';

const redactPaths = [
  'token',
  'tokens',
  'accessToken',
  'refreshToken',
  'accessKey',
  'password',
  'adminPassword',
  'newPassword',
  'confirmPassword',
  'passwordHash',
  'tokenHash',
  'newTokenHash',
  'secret',
  'authorization',
  'cookie',
  '*.token',
  '*.tokens',
  '*.accessToken',
  '*.refreshToken',
  '*.accessKey',
  '*.password',
  '*.adminPassword',
  '*.newPassword',
  '*.confirmPassword',
  '*.passwordHash',
  '*.tokenHash',
  '*.newTokenHash',
  '*.secret',
  '*.authorization',
  '*.cookie',
  '*.*.token',
  '*.*.tokens',
  '*.*.accessToken',
  '*.*.refreshToken',
  '*.*.accessKey',
  '*.*.password',
  '*.*.adminPassword',
  '*.*.newPassword',
  '*.*.confirmPassword',
  '*.*.passwordHash',
  '*.*.tokenHash',
  '*.*.newTokenHash',
  '*.*.secret',
  '*.*.authorization',
  '*.*.cookie',
  'req.headers.cookie',
  'req.headers.authorization',
  'req.body.token',
  'req.body.tokens',
  'req.body.password',
  'req.body.adminPassword',
  'req.body.newPassword',
  'req.body.confirmPassword',
  'req.body.passwordHash',
  'req.body.accessToken',
  'req.body.refreshToken',
  'req.body.accessKey',
  'req.body.tokenHash',
  'req.body.newTokenHash',
  'req.body.secret',
  'REDIS_PASSWORD',
  'MEILISEARCH_MASTER_KEY',
  'GITHUB_CLIENT_SECRET',
  'YANDEX_CLIENT_SECRET',
  'GOOGLE_CLIENT_SECRET',
  'AUTH_DATABASE_URL',
  'USER_DATABASE_URL',
  'CHAT_DATABASE_URL',
  'NOTIFICATION_DATABASE_URL',
  'MEDIA_DATABASE_URL',
  'RABBITMQ_URL',
  'MINIO_ACCESS_KEY',
  'POSTGRES_PASSWORD',
  'RABBITMQ_PASSWORD',
  'GRAFANA_ADMIN_PASSWORD',
  'JWT_ACCESS_SECRET',
  'JWT_REFRESH_SECRET',
  'MINIO_SECRET_KEY',
  'SMTP_PASSWORD',
  'VAPID_PRIVATE_KEY',
];

export function createLoggerOptions(serviceName: string): Params {
  const level = process.env['LOG_LEVEL'] ?? 'info';
  const isPretty = process.env['LOG_FORMAT'] === 'pretty';

  return {
    pinoHttp: {
      level,
      redact: { paths: redactPaths, remove: true },
      customProps: () => ({
        service: serviceName,
        env: process.env['DEPLOYMENT_ENVIRONMENT'] ?? process.env['NODE_ENV'] ?? 'development',
      }),
      transport: isPretty
        ? {
            target: 'pino-pretty',
            options: { singleLine: true, colorize: true },
          }
        : undefined,
    },
  };
}
