import type { CSSProperties } from 'react';

type PrismTheme = Record<string, CSSProperties>;

export const appPrismTheme: PrismTheme = {
  'code[class*="language-"]': {
    color: '#ffffff',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '0.75rem',
    lineHeight: '1.6',
    background: 'none',
  },
  'pre[class*="language-"]': {
    color: '#ffffff',
    background: 'transparent',
    margin: 0,
    padding: 0,
    overflow: 'auto',
  },
  comment: { color: '#808080', fontStyle: 'italic' },
  prolog: { color: '#808080' },
  doctype: { color: '#808080' },
  cdata: { color: '#808080' },
  punctuation: { color: '#8badc1' },
  property: { color: '#80cbc4' },
  keyword: { color: 'var(--color-purple-70)', fontStyle: 'italic' },
  tag: { color: '#f07178' },
  'class-name': { color: '#ffcb6b' },
  boolean: { color: 'var(--color-purple-80)' },
  constant: { color: 'var(--color-purple-80)' },
  symbol: { color: '#f07178' },
  deleted: { color: '#f07178' },
  number: { color: '#f78c6c' },
  selector: { color: '#c3e88d' },
  'attr-name': { color: '#c792ea' },
  string: { color: '#c3e88d' },
  char: { color: '#c3e88d' },
  builtin: { color: '#ffcb6b' },
  inserted: { color: '#c3e88d' },
  operator: { color: '#89ddff' },
  url: { color: '#89ddff' },
  variable: { color: '#ffffff' },
  atrule: { color: '#ffcb6b' },
  'attr-value': { color: '#c3e88d' },
  function: { color: '#82aaff' },
  'function-variable': { color: '#82aaff' },
  regex: { color: '#f78c6c' },
  important: { color: 'var(--color-purple-70)', fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};
