import type { CSSProperties } from 'react';

// Mapped from project palette: global.css @theme
const t = {
  gray50:    '#808080',
  gray15:    '#262626',
  gray10:    '#1a1a1a',
  purple65:  '#8254f8',
  purple70:  '#946cf9',
  purple80:  '#a885fa',
  purple90:  '#dbcefd',
  white:     '#ffffff',
} as const;

export const prismTheme: Record<string, CSSProperties> = {
  'pre[class*="language-"]': {
    background: 'transparent',
    margin: 0,
    padding: 0,
    overflow: 'auto',
  },
  'code[class*="language-"]': {
    color: t.white,
    fontFamily: 'ui-monospace, monospace',
    fontSize: '0.75rem',
    lineHeight: '1.6',
  },
  comment:     { color: t.gray50 },
  prolog:      { color: t.gray50 },
  doctype:     { color: t.gray50 },
  cdata:       { color: t.gray50 },
  punctuation: { color: t.gray50 },
  keyword:     { color: t.purple70 },
  operator:    { color: t.purple70 },
  important:   { color: t.purple70, fontWeight: '600' },
  atrule:      { color: t.purple70 },
  string:      { color: t.purple90 },
  'attr-value':{ color: t.purple90 },
  char:        { color: t.purple90 },
  regex:       { color: t.purple90 },
  function:    { color: t.purple65 },
  'class-name':{ color: t.purple65 },
  selector:    { color: t.purple65 },
  tag:         { color: t.purple65 },
  number:      { color: t.purple80 },
  boolean:     { color: t.purple80 },
  constant:    { color: t.purple80 },
  symbol:      { color: t.purple80 },
  builtin:     { color: t.purple80 },
  namespace:   { color: t.purple80, opacity: 0.85 },
  variable:    { color: t.white },
  parameter:   { color: t.white },
  'attr-name': { color: t.white },
  property:    { color: t.white },
  inserted:    { color: t.purple90 },
  deleted:     { color: t.gray50, textDecoration: 'line-through' },
  bold:        { fontWeight: '600' },
  italic:      { fontStyle: 'italic' },
};
